import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {chromium} from 'playwright';
import {createServer} from 'vite';

const project=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const root=path.dirname(project),assets=path.join(project,'public/codex_genre'),qa=path.join(project,'qa/v6');
await mkdir(assets,{recursive:true});await mkdir(qa,{recursive:true});
process.chdir(root);
const demo=JSON.parse(await readFile(path.join(project,'public/codex_light/codex_demo_data.json'),'utf8'));
const entries=demo.entries.map((entry,index)=>index===0?{...entry,tags:[]}:entry);
const version=JSON.parse(await readFile(path.join(root,'package.json'),'utf8')).version;
const server=await createServer({configFile:path.join(root,'mobile/vite.config.ts'),cacheDir:path.join(project,'.cache/vite_genre'),server:{host:'127.0.0.1',port:0,strictPort:true,forwardConsole:false}});
let browser;
try{
 await server.listen();const origin=`http://127.0.0.1:${server.httpServer.address().port}`;
 browser=await chromium.launch({channel:'chrome',headless:true});
 const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:3,timezoneId:'Asia/Shanghai',locale:'zh-CN',colorScheme:'light'});
 const page=await context.newPage(),errors=[];
 page.on('pageerror',error=>errors.push(error.message));page.setDefaultTimeout(15000);
 await page.clock.setFixedTime(new Date('2026-09-29T12:00:00+08:00'));
 await page.route('**/*',route=>{try{if(new URL(route.request().url()).origin===origin)return route.continue();}catch{}return route.abort();});
 await page.goto(origin+'/#/privacy');
 await page.evaluate(entries=>{
  localStorage.setItem('music-feelings-mobile-entries',JSON.stringify(entries));
  localStorage.setItem('abu-theme-choice-v1','light');
  localStorage.setItem('codex-reading-preferences-v1',JSON.stringify({size:'normal',dark:false}));
 },entries);
 await page.goto(origin+'/#/entries/'+entries[0].id+'/edit');await page.locator('.writing-form').waitFor();
 await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(500);
 const tree=page.locator('.genre-tree'),roots=tree.locator(':scope > div');
 const majorCategories=await roots.locator(':scope > .genre-tree-level > button').allTextContents();
 assert.equal(majorCategories.length,16);assert.deepEqual(majorCategories.slice(0,8),['流行','摇滚','电子','Hip-Hop / Rap','R&B / Soul','爵士','古典','蓝调']);
 const recordsBefore=await page.evaluate(()=>localStorage.getItem('music-feelings-mobile-entries'));
 const manifest={version,theme:'light',capture:'Current GenrePicker DOM; actual expand/select clicks; isolated fictional data',viewport:{width:390,height:844,scale:3},majorCategories,visibleMajorCategories:majorCategories.slice(0,8),path:['电子','House','Deep House'],assets:{},layout:{}};
 const sizes={};
 const capture=async(name,start,end,button)=>{
  await start.scrollIntoViewIfNeeded();
  const initial=await start.boundingBox();assert(initial);
  await page.evaluate(y=>window.scrollTo(0,window.scrollY+y-20),initial.y);
  await page.waitForTimeout(250);
  const first=await start.boundingBox(),last=await end.boundingBox(),point=button?await button.boundingBox():null;
  assert(first&&last&&first.y>=0);assert.equal(await page.evaluate(()=>document.documentElement.dataset.theme),'light');
  const clip={x:first.x,y:first.y,width:first.width,height:last.y+last.height-first.y};
  assert(clip.height>0&&clip.y+clip.height<=844,'Real excerpt must fit the capture viewport');
  const file=`codex_${name}.png`;
  const bytes=await page.screenshot({type:'png',path:path.join(assets,file),clip,animations:'disabled',style:'.app-header,.bottom-nav,.entry-save-actions{visibility:hidden!important}'});
  const size=[bytes.readUInt32BE(16),bytes.readUInt32BE(20)];sizes[file]=size;
  manifest.assets[name]={file,route:page.url().replace(origin,''),source:'Unmodified DOM excerpt; crop only; fixed navigation hidden during capture',size};
  if(point)manifest.layout[name]={centerX:Math.round((point.x+point.width/2-clip.x)*3),centerY:Math.round((point.y+point.height/2-clip.y)*3)};
  console.log('captured',name,size);
 };
 // Expanded-node arrows are CSS ::after content; match the actual DOM label.
 const electronic=tree.getByRole('button').filter({hasText:/^电子$/});
 await capture('genre_overview',tree,roots.nth(7),electronic);
 await electronic.click();
 const electronicRoot=roots.filter({has:page.getByRole('button').filter({hasText:/^电子$/})});
 assert.equal(await electronicRoot.count(),1);
 const subcategories=electronicRoot.locator(':scope > div').nth(1).locator(':scope > div');
 assert.deepEqual((await subcategories.locator(':scope > .genre-tree-level > button').allTextContents()).slice(0,5),['House','Techno','Trance','Drum and Bass','Dubstep']);
 const house=electronicRoot.getByRole('button').filter({hasText:/^House$/});
 await capture('genre_electronic',electronicRoot,subcategories.nth(4),house);
 await house.click();
 const houseRoot=subcategories.filter({has:page.getByRole('button').filter({hasText:/^House$/})});
 const leaves=houseRoot.locator(':scope > div').nth(1).locator('.genre-tree-level > button');
 manifest.houseChildren=await leaves.allTextContents();assert.equal(manifest.houseChildren.length,17);assert(manifest.houseChildren.includes('Deep House'));
 const deep=houseRoot.getByRole('button',{name:'Deep House',exact:true});
 manifest.visibleHouseChildren=manifest.houseChildren.slice(0,6);
 await capture('genre_house',electronicRoot,leaves.nth(5),deep);
 await deep.click();assert(await deep.evaluate(element=>element.classList.contains('selected')));
 await capture('genre_selected',electronicRoot,leaves.nth(5));
 manifest.selectedTags=await page.locator('input[name="genreTags"]').inputValue();assert.equal(manifest.selectedTags,'电子, House, Deep House');
 assert.equal(await page.evaluate(()=>localStorage.getItem('music-feelings-mobile-entries')),recordsBefore);
 assert.deepEqual(errors,[]);manifest.errors=errors;manifest.generatedAt=new Date().toISOString();
 await writeFile(path.join(assets,'codex_assets.json'),JSON.stringify(manifest,null,2));
 await writeFile(path.join(assets,'codex_sizes.json'),JSON.stringify(sizes,null,2));
 await writeFile(path.join(qa,'codex_capture_genre.json'),JSON.stringify({passed:true,version,theme:'light',syntheticOnly:true,recordsUnchanged:true,majorCategories,path:manifest.path,houseChildren:manifest.houseChildren,selectedTags:manifest.selectedTags,assets:manifest.assets,layout:manifest.layout,errors},null,2));
 console.log('PASS actual three-level genre capture');
}finally{await browser?.close();await server.close();}
