import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { makeJournalFixtures } from '../mobile/codex_journal_fixtures.mjs';
const origin = 'http://127.0.0.1:5173';
const output = 'release/codex_ux_qa';
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ headless: true, channel: 'chrome' });
try {
  const page = await browser.newPage({ viewport: { width: 390, height: 844 }, timezoneId: 'Asia/Shanghai' });
  page.setDefaultTimeout(15000);
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto(origin);
  const entries = makeJournalFixtures('6');
  await page.evaluate(items => localStorage.setItem('music-feelings-mobile-entries', JSON.stringify(items)), entries);
  await page.reload();
  await page.locator('.home-entry-row').first().waitFor();
  assert.match(await page.locator('.home-entry-meta').allTextContents().then(a => a.join(' ')), /7\.5.*\/ 10/);
  assert.doesNotMatch(await page.locator('.home-entry-meta').allTextContents().then(a => a.join(' ')), /★|3\.8/);
  assert.doesNotMatch(await page.locator('.home-entry-heading time').allTextContents().then(a => a.join(' ')), /12-01/);
  assert.ok(await page.locator('.home-entry-list').evaluate(el => el.getBoundingClientRect().top) < await page.locator('.home-visual-links').evaluate(el => el.getBoundingClientRect().top));
  await page.screenshot({ path: output + '/codex_home_new.png', fullPage: true });
  await page.goto(origin + '/#/new');
  const body = page.locator('textarea[name="content"]'); await body.waitFor();
  assert.ok((await body.boundingBox()).y < 844, 'Body begins on first mobile screen');
  assert.equal(await page.locator('.writing-extras').getAttribute('open'), null);
  assert.doesNotMatch(await page.locator('select[name="type"]').innerText(), /album|song/);
  await page.screenshot({ path: output + '/codex_writer_new.png', fullPage: true });
  await page.locator('input[name="title"]').fill('正文先写的草稿');
  await body.fill('这是草稿正文，稍后接着写。');
  await page.locator('.writing-extras > summary').click();
  await page.locator('input[name="albumName"]').fill('补充信息也要保存');
  await page.locator('.writing-extras > summary').click();
  await page.getByRole('button', { name: '保存草稿', exact: true }).click();
  await page.getByRole('button', { name: /正文先写的草稿/ }).waitFor();
  await page.goto(origin + '/#/');
  await page.getByText('这是草稿正文，稍后接着写。', { exact: true }).waitFor();
  await page.goto(origin + '/#/drafts');
  await page.getByRole('button', { name: /正文先写的草稿/ }).click();
  await body.waitFor(); assert.equal(await body.inputValue(), '这是草稿正文，稍后接着写。');
  assert.equal(await page.locator('input[name="albumName"]').inputValue(), '补充信息也要保存');
  await page.getByRole('button', { name: '保存正式乐评', exact: true }).click();
  await page.waitForURL('**/#/entries/*');
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('music-feelings-mobile-entries')).find(e => e.title === '正文先写的草稿')?.albumName), '补充信息也要保存');
  await page.evaluate(items => localStorage.setItem('music-feelings-mobile-entries', JSON.stringify(items)), entries);
  await page.goto(origin + '/#/summary?year=2026');
  await page.locator('.journal-editor summary').first().click();
  await page.getByLabel('封面作品', { exact: true }).selectOption(entries[0].id);
  await page.getByLabel('给这一年的话（选填，最多 120 字）').fill('今年留下这些记录。');
  const checks = page.locator('.journal-editor input[type="checkbox"]');
  for (let i = 0; i < 3; i++) await checks.nth(i).check();
  assert.equal(await checks.nth(3).isDisabled(), true);
  const quote = page.locator('.journal-editor textarea').nth(1);
  await quote.fill('这不是正文里的原句');
  await page.getByRole('button', { name: '保存年度精选' }).click();
  await page.getByText('摘录须为对应正文中连续的一段原话，请检查后保存。', { exact: true }).waitFor();
  await quote.fill(entries[0].content.slice(0, 24));
  await page.getByRole('button', { name: '保存年度精选' }).click();
  await page.getByText('年度精选已保存', { exact: true }).waitFor();
  await page.reload();
  await page.getByRole('heading', { name: '我的年度代表作品' }).waitFor();
  await page.locator('.journal-quote p').filter({ hasText: '今年留下这些记录。' }).waitFor();
  assert.equal(await page.locator('.journal-contents a').count(), 2);
  assert.equal(await page.locator('.journal-type-cover').count(), 1);
  const backup = await page.evaluate(async () => {
    const { store } = await import('/src/store.ts');
    return JSON.parse(await store.exportBackup()).appData;
  });
  assert.equal(JSON.parse(backup['journal-edition:2026']).entryIds.length, 3);
  assert.equal(JSON.parse(backup['journal-edition:2026']).coverId, entries[0].id);
  await page.screenshot({ path: output + '/codex_curated_new.png', fullPage: true });
  const privacy = await page.evaluate(async entries => {
    const { planJournalPages, renderJournalPage } = await import('/src/codex_yearbookPages.ts');
    const options = { hideContent: true, hideDate: true, hideRating: true, edition: { coverId: entries[0].id, entryIds: [entries[0].id], quotes: {}, message: '绝不能导出的私密寄语' } };
    const texts = []; const old = CanvasRenderingContext2D.prototype.fillText;
    CanvasRenderingContext2D.prototype.fillText = function (s, ...args) { texts.push(s); return old.call(this, s, ...args); };
    try {
      for (const kind of ['works', 'index', 'cover', 'overview']) {
        const pages = await planJournalPages(2026, entries, kind, options);
        for (const [i, p] of pages.entries()) await renderJournalPage(2026, entries, p, i, pages.length, new Date(), options);
      }
    } finally { CanvasRenderingContext2D.prototype.fillText = old; }
    return texts.join('\n');
  }, entries);
  assert.doesNotMatch(privacy, /记录于|整理于|7\.5|\/ 10|绝不能导出/);
  assert.ok(!privacy.includes(entries[0].content.slice(0, 15)));
  await page.goto(origin + '/#/summary?year=2026&view=overview');
  await page.getByRole('button', { name: '分批保存全年作品全文' }).click();
  await page.locator('.journal-export-preview').waitFor();
  const footer = page.locator('.journal-export-footer');
  const rect = await footer.boundingBox(); assert.ok(rect.y + rect.height <= 844);
  await page.getByRole('button', { name: '选择全部页', exact: true }).click();
  assert.match(await footer.innerText(), /已选 6 页/);
  await page.evaluate(() => {
    window.codexShared = [];
    Object.defineProperty(navigator, 'canShare', { configurable: true, value: () => true });
    Object.defineProperty(navigator, 'share', { configurable: true, value: async ({ files }) => { window.codexShared = files.map(f => f.name); } });
  });
  await page.getByRole('button', { name: '系统分享', exact: true }).click();
  await page.getByRole('button', { name: '系统分享（已准备）' }).click();
  await page.getByText('已打开系统分享', { exact: true }).waitFor();
  assert.equal(await page.evaluate(() => window.codexShared.length), 6);
  await page.locator('.journal-privacy summary').click();
  await page.getByLabel('隐藏正文、摘录、寄语与标签').check();
  await page.locator('.journal-export-preview').waitFor();
  assert.match(await footer.innerText(), /已选 1 页/);
  assert.equal(await page.getByRole('button', { name: '系统分享（已准备）' }).count(), 0);
  await page.screenshot({ path: output + '/codex_export_new.png' });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.getByRole('button', { name: '关闭图片预览' }).click();
  await page.evaluate(id => {
    const items = JSON.parse(localStorage.getItem('music-feelings-mobile-entries'));
    localStorage.setItem('music-feelings-mobile-entries', JSON.stringify(items.filter(e => e.id !== id)));
  }, entries[0].id);
  await page.goto(origin + '/#/summary?year=2026'); await page.reload();
  await page.locator('.journal-editor').waitFor();
  await page.locator('.journal-editor summary').first().click();
  assert.notEqual(await page.getByLabel('封面作品', { exact: true }).inputValue(), entries[0].id);
  assert.ok(!(await page.locator('.journal-quote p').allTextContents()).includes(entries[0].content.slice(0, 24)));
  assert.deepEqual(errors, []);
  console.log('PASS: ten-point rating/date, home order, first-screen editor, collapsed draft restore, curated quotes/backup/reload, all PNG privacy paths, selected multi-share, footer and privacy invalidation. Simulated data only.');
} finally { await browser.close(); }
